### ISSUE TITLE
Do not display warning re: top n when response neurons are selected

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/neuron-simulator#22]
### Feature Inspiration

When specific response neurons are selected, a warning is always displayed above the plot, regardless of what value is entered in the "display top n neurons". While it's nice to let the user know that an input is ignored, there is no way for them to avoid this atm.

### Feature Description

A suggestion would be to only display this when Top N is explicitly set *and* response neurons are selected. I'd also suggest that the warning be moved to next to the Top N field and not by the plot.

### Alternatives Considered

A brief description of any alternative features that may accomplish the same
ultimate goal.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by fkang-pu** [comment]
Just took a look and seems this issue already fixed . No warning was displayed with a few response neurons were selected. I close this issue.
