### ISSUE TITLE
Make the Plot button more obviously the default

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/neuron-simulator#23]
### Feature Inspiration

To me, the position, size, and color make the "Start Over" button the first button I hit instinctively. 

### Feature Description

A few suggestions:
1. Move the Plot button to the right. That seems to be the "default" place for a "next" type action.
2. Make the "Start Over" button grey, and smaller. 

### Alternatives Considered

A brief description of any alternative features that may accomplish the same
ultimate goal.

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by fkang-pu** [comment]
This issue was already addressed a while ago, closing it.
