### ISSUE TITLE
Update plot notes

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/neuron-simulator#51]
### Feature Inspiration

Clarify notes for plots

### Feature Description

In the note that is displayed above the plot, change the word “data “ to “empirical measurements”:
> Some connections are missing because we don't have ~data~ *empirical measurements* for them

### Comment

**Comment by fkang-pu** [comment]
Pushed requested change to a fork, and created a [pull request](https://github.com/leiferlab/worm-functional-connectivity/pull/10).

**Comment by lparsons** [comment]
I believe this is done and can be closed.
